- name: create ec2user and update route 53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-05f4a262320964a82 # replace with your SG ID
    zone_id: "Z05390352I6EFXPEJQ0I3" # replace with your ID
    domain_name: "arjundevops27.fun"
    instances: 
    - mongodb
    # - redis
    # - mysql
    # - rabbitmq

  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
     name: "{{ item}}"
     instance_type: t3.micro
     security_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
     tags:
        Name: "{{ item }}"

    loop: "{{instances}}"

    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
     
   